apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-chart.fullname" . }}-db-secret
type: Opaque
stringData:
  db-user: {{ .Values.dbConfig.user | quote }}
  db-password: {{ .Values.dbConfig.password | quote }}
