apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials-sync
  namespace: db-space
spec:
  refreshInterval: "55m" # How often to check Vault for updates
  secretStoreRef:
    name: vault-backend-dynamic-db
    kind: SecretStore
  target:
    # This is the name of the ACTUAL K8s secret that will be created
    name: app-db-secret 
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: creds/app-role
      property: username
  - secretKey: password
    remoteRef:
      key: creds/app-role
      property: password
