apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-dynamic-db
  namespace: db-space
spec:  
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "database"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "app-market-role"
          serviceAccountRef:
            name: db-sa
